"""The feature-bank contract: one Crop in, one FeatureResult out, written where the harness expects it.

FROZEN after Phase 0 (contract version 2, 3 Oct 23:xx: see bank/CONTRACT_REQUESTS.md for what changed). Ask for a
change in bank/CONTRACT_REQUESTS.md; do not edit this file from a family lane.

    from bank.core import Crop, FeatureResult, load_crop, tiles, block_mean, quantise

    FAMILY = "phase"                                   # bank/families/phase.py
    def extract(crop, cfg):
        res = FeatureResult(FAMILY)
        void = crop.phase("void")
        res.scalar("BSE", "phase", 25, "void_frac_mid", void.mean(), length_um=None, tag="material")
        return res

Run a family (2 smoke crops first, then every crop, then the perturbations):

    python -m bank.run fam phase --sites smoke --perts P0
    python -m bank.run fam phase --sites all --perts P0
    python -m bank.run fam phase --sites all --perts imaging

What a family may use: the Crop's views, phase maps, valid mask and helper functions below. Nothing else.
What no feature may ever see: image height or width, file or folder names, the crop id, which source image a
crop came from, tile positions, or anything in meta/analysis_only.csv. Those exist for splits, nulls and
diagnostics only. Every Crop has the same shape for that reason.

Layout under processed/bank/ (not in git):
    views/<pert>/<crop>.npz                  raw windows, phase maps and anchors of one crop version
    feat/<family>/<pert>/<crop>.parquet      one row of scalars, columns named family|det|view|scale_nm|stat
    feat/<family>/<pert>/<crop>.npz          high-dimensional blocks and per-tile arrays
    feat/<family>/<pert>/<crop>.done         written last: the crop version is complete
    feat/<family>/catalog.parquet            one row per column or block: what it is and how to treat it
    _status.jsonl                            one line per finished job
"""
import json
import os
import re
import sys
import time
import zlib
from dataclasses import dataclass, field
from pathlib import Path

import numpy as np
import pandas as pd
from scipy import ndimage as ndi

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))   # so `preprocessing`, `features`, `representation` import

from features._common import harmonise as H                                       # noqa: E402
from preprocessing import PROCESSED_DIR, ROOT, load_grey, raw_path                 # noqa: E402
from representation.embed import INJECT_SITES, INJECTIONS, PERTURBATIONS           # noqa: E402
from representation.embed import inject as _inject, perturb as _perturb            # noqa: E402

BANK_DIR = PROCESSED_DIR / "bank"
VIEWS_DIR = BANK_DIR / "views"
FEAT_DIR = BANK_DIR / "feat"
STATUS_LOG = BANK_DIR / "_status.jsonl"
META_DIR = ROOT / "meta"

PX_NM = 25.0                         # one pixel, from the TIF resolution tag; identical for every image
WINDOW = (1336, 6944)                # every Crop has exactly this shape (rows, columns)
P0 = "P0"                            # the crop as acquired
IMAGING_PERTS = tuple(PERTURBATIONS)         # synthetic imaging changes, applied to the raw image before harmonising
MATERIAL_INJECTS = tuple(INJECTIONS)         # known material changes painted into the raw image (controls)
INJECT_CROPS = tuple(INJECT_SITES)
SMOKE_CROPS = ("r17byphk", "kbdh4tri")
DETECTORS = ("BSE", "Inlens")        # the two detectors every crop has
LEAKRISK_DETECTORS = ("SE",)         # ETD/SE: the file name marks one source image, so tag anything from it leakrisk
CROSS_DETECTORS = ("BSExInlens",)    # the detector name for statistics that need both detectors at once
VIEWS = ("raw", "anchored", "harmonised", "smoothed")
SCALES = (1, 2, 4, 8)                # block-mean factors; scale_nm = 25 * factor
TAGS = ("material", "imaging", "mixed", "leakrisk")
SMOOTH_SIGMA_PX = 2.5                # the smoothed view, for phase work; fine texture uses the unsmoothed views
BRIGHT_BAND_G = 0.15                 # bright_lo / bright_hi: the bright threshold moved by this many graphite units
VOID_BAND_G = 0.05                   # void_lo / void_hi likewise
PHASES = ("void", "void_lo", "void_hi", "bright", "bright_lo", "bright_hi", "bright_fixed", "dim")
DERIVED_PHASES = ("graphite",)       # graphite = none of void, bright, dim; made on demand, not stored
# Fixed, global grey ranges for quantising (never per-image min/max).
QUANT_RANGE = {"raw": (0.0, 255.0), "BSE": (-0.5, 3.0), "Inlens": (0.0, 1.0), "SE": (0.0, 1.0)}
# Name parts that would let a model see provenance. Checked token by token on every column and block name.
FORBIDDEN_TOKENS = {"height", "width", "aspect", "folder", "batch", "file", "filename", "name", "site", "crop", "session",
                    "source", "image", "strip", "chain", "neighbour", "neighbor", "join", "position", "pos", "row", "col",
                    "index", "idx", "id", "path", "split", "fold", "label", "target"}


# ----------------------------------------------------------------------------------------------------
# provenance: for the runner, splits, nulls and diagnostics. Never for features.
# ----------------------------------------------------------------------------------------------------
def crops_table():
    """meta/crops.csv: site, folder, source_image."""
    return pd.read_csv(META_DIR / "crops.csv")


def all_crops():
    return tuple(crops_table().site)


def crop_versions(crops="all", perts=P0):
    """Expand the shorthand used on the command line into (crop, pert) pairs."""
    ids = all_crops()
    names = {"all": ids, "smoke": SMOKE_CROPS, "inject": INJECT_CROPS}.get(crops, None) if isinstance(crops, str) else tuple(crops)
    if names is None:
        names = tuple(c for c in crops.split(",") if c)
    unknown = sorted(set(names) - set(ids))
    if unknown:
        raise ValueError(f"unknown crops {unknown}")
    kinds = {P0: (P0,), "imaging": IMAGING_PERTS, "inject": MATERIAL_INJECTS,
             "all": (P0,) + IMAGING_PERTS + MATERIAL_INJECTS}.get(perts, None) if isinstance(perts, str) else tuple(perts)
    if kinds is None:
        kinds = tuple(p for p in perts.split(",") if p)
    return [(c, p) for p in kinds for c in names if p not in MATERIAL_INJECTS or c in INJECT_CROPS]


# ----------------------------------------------------------------------------------------------------
# small image helpers every family shares
# ----------------------------------------------------------------------------------------------------
def block_mean(arr, factor):
    """Downsample by an integer factor with a block mean (no interpolation, so pixel size stays exact)."""
    if factor == 1:
        return arr
    h, w = (arr.shape[0] // factor) * factor, (arr.shape[1] // factor) * factor
    return arr[:h, :w].astype(np.float32).reshape(h // factor, factor, w // factor, factor).mean(axis=(1, 3))


def tiles(arr, size, stride=None):
    """(n, size, size) stack of tiles in a fixed order. Positions are deliberately not returned."""
    stride = stride or size
    ys = range(0, arr.shape[0] - size + 1, stride)
    xs = range(0, arr.shape[1] - size + 1, stride)
    return np.stack([arr[y:y + size, x:x + size] for y in ys for x in xs])


def quantise(arr, kind, levels):
    """Integer grey levels 0..levels-1 over the fixed global range of `kind` ("raw", "BSE", "Inlens", "SE")."""
    lo, hi = QUANT_RANGE[kind]
    q = np.floor((np.asarray(arr, np.float32) - lo) / (hi - lo) * levels)
    return np.clip(q, 0, levels - 1).astype(np.int32)


def column(family, det, view, scale_nm, stat):
    return f"{family}|{det}|{view}|{int(scale_nm)}|{stat}"


def forbidden_tokens(name):
    """The forbidden tokens in a column or block name (empty set = fine). Plural and numbered forms count too:
    tile_rows, fold3 and n_images are refused just like row, fold and image."""
    bad = set()
    for token in re.split(r"[^a-z0-9]+", name.lower()):
        stem = token.rstrip("0123456789")
        for form in (token, stem, stem[:-1] if stem.endswith("s") else "", stem[:-2] if stem.endswith("es") else "",
                     "index" if stem == "indices" else ""):
            if form in FORBIDDEN_TOKENS:
                bad.add(token)
    return bad


# ----------------------------------------------------------------------------------------------------
# the Crop
# ----------------------------------------------------------------------------------------------------
@dataclass
class Crop:
    """One crop version: the common window of one site under one perturbation.

    raw       {"BSE", "Inlens", "SE"} -> uint8 (1336, 6944), channel 0 of the TIF, 8 edge columns trimmed
    anchors   black level and graphite level in raw grey levels, thresholds in graphite units, noise levels.
              These describe the imaging, not the material: a feature built on them must be tagged "imaging".
    masks     the phase maps and the valid mask, all bool (1336, 6944)
    pert      "P0" or the perturbation / injection applied to the raw image before harmonising
    """
    raw: dict
    anchors: dict
    masks: dict
    pert: str = P0
    _id: str = ""                                    # for the runner and diagnostics only; never read it in a family
    _cache: dict = field(default_factory=dict, repr=False)

    @property
    def shape(self):
        return WINDOW

    def view(self, det, view="anchored", scale=1):
        """One detector in one view, block-averaged by `scale` (1, 2, 4, 8).

        raw         uint8 grey levels as stored (after the perturbation)
        anchored    BSE in graphite units (0 = black level, 1 = graphite); Inlens and SE rank-normalised to 0..1.
                    No noise added: use it for intensity statistics and as model input.
        harmonised  anchored plus Gaussian noise up to one fixed level, so every crop is equally noisy.
                    Use it for fine texture (< 500 nm), where noise would otherwise mark the imaging session.
        smoothed    anchored blurred by sigma = 2.5 px. Use it for phase work, never for fine texture.
        """
        key = (det, view, scale)
        if key not in self._cache:
            base = (det, view, 1)
            if base not in self._cache:
                self._cache[base] = self._full(det, view)
            self._cache[key] = block_mean(self._cache[base], scale)
        return self._cache[key]

    def _full(self, det, view):
        if view == "raw":
            return self.raw[det]
        if view == "anchored":
            if det == "BSE":
                return (self.raw["BSE"].astype(np.float32) - np.float32(self.anchors["black"])) / np.float32(self.anchors["scale"])
            return H.rank_normalise(self.raw[det])
        if view == "harmonised":
            a = self.view(det, "anchored")
            target = {"BSE": H.CFG["noise"]["bse_target_sigma"]}.get(det, H.CFG["noise"]["inlens_target_sigma"])
            sigma = self.anchors["bse_noise_sigma"] if det == "BSE" else self.anchors["inlens_noise_sigma"]
            extra = float(np.sqrt(max(target ** 2 - sigma ** 2, 0.0)))
            if extra == 0.0:
                return a
            rng = np.random.default_rng(self.anchors["seed"] + DETECTORS.index(det) if det in DETECTORS else self.anchors["seed"] + 7)
            return a + rng.standard_normal(a.shape, dtype=np.float32) * np.float32(extra)
        if view == "smoothed":
            return ndi.gaussian_filter(self.view(det, "anchored"), SMOOTH_SIGMA_PX)
        raise ValueError(f"unknown view {view!r}: use one of {VIEWS}")

    def phase(self, name="void"):
        """A phase map (bool). void / bright are the decision recipe; the _lo and _hi versions move the threshold by
        VOID_BAND_G / BRIGHT_BAND_G graphite units so that a fraction can always be reported as lo / mid / hi.
        _lo is the stricter threshold (smaller phase), _hi the looser one. "graphite" is what is left: not void,
        not bright, not dim."""
        if name == "graphite":
            if "graphite" not in self._cache:
                self._cache["graphite"] = ~(self.masks["void"] | self.masks["bright"] | self.masks["dim"])
            return self._cache["graphite"]
        return self.masks[name]

    @property
    def valid(self):
        """False where the raw BSE is saturated (and 2 px around it). Exclude those pixels from statistics."""
        return self.masks["valid"]


def _phase_maps(h, raw_bse_window):
    """lo / mid / hi maps of the harmonised window."""
    seg = H.CFG["segmentation"]
    t_void, t_bright = h.acq["void_threshold"], h.acq["bright_threshold"]
    bright_blur = ndi.gaussian_filter(h.bse, seg["bright_blur_sigma_px"])

    def void_at(t):
        return H.fill_small_holes(H.drop_small(h.bse_blur < t, seg["min_void_px"]), seg["min_void_px"])

    maps = {"void": h.void, "void_lo": void_at(t_void - VOID_BAND_G), "void_hi": void_at(t_void + VOID_BAND_G),
            "bright": h.bright, "bright_lo": H._bright_mask(bright_blur, t_bright + BRIGHT_BAND_G),
            "bright_hi": H._bright_mask(bright_blur, t_bright - BRIGHT_BAND_G), "bright_fixed": h.bright_fixed, "dim": h.dim}
    maps = {k: np.ascontiguousarray(v) for k, v in maps.items()}
    maps["valid"] = ~ndi.binary_dilation(raw_bse_window == 255, iterations=2)
    return maps


def common_window(shape):
    """(r0, r1, x0, x1): the rows and columns of the common window inside a raw image of this shape.

    harmonise.crop_box picks the rows (250..H-25, then the central 1336) and trims 8 columns each side; the Crop keeps
    the central 6944 of the remaining columns.
    """
    r0, r1, c0, c1 = H.crop_box(*shape)
    if r1 - r0 < WINDOW[0] or c1 - c0 < WINDOW[1]:
        raise ValueError(f"image {tuple(shape)} is too small for the common window {WINDOW}")
    x0 = c0 + (c1 - c0 - WINDOW[1]) // 2
    return r0, r1, x0, x0 + WINDOW[1]


def make_crop(raw_bse, raw_inlens, raw_se=None, pert=P0, crop_id="", seed=None):
    """Raw images of one site (2D uint8, at least 1611 rows and 6960 columns) -> Crop.

    Anchors, noise levels, thresholds and phase maps are computed on exactly the pixels the Crop holds: harmonise is
    handed the common columns plus the 8 it trims on each side, and nothing else. So a Crop does not depend on the
    image width, on what lies outside the window, or on any name: the noise seed comes from the window's content.
    """
    se = raw_inlens if raw_se is None else raw_se
    r0, r1, x0, x1 = common_window(raw_bse.shape)
    side = H.CFG["crop"]["side_px"]
    window = {d: np.ascontiguousarray(img[r0:r1, x0:x1]) for d, img in (("BSE", raw_bse), ("Inlens", raw_inlens), ("SE", se))}
    if seed is None:
        seed = zlib.crc32(window["BSE"].tobytes())
    h = H.harmonise_arrays(*(img[:, x0 - side:x1 + side] for img in (raw_bse, raw_inlens, se)), seed)
    if h.shape != WINDOW:
        raise ValueError(f"harmonise returned {h.shape}, expected {WINDOW}")
    a = h.acq
    anchors = dict(black=float(a["bse_black_raw"]), graphite=float(a["bse_graphite_raw"]),
                   scale=float(max(a["bse_graphite_raw"] - a["bse_black_raw"], 1.0)),
                   bse_noise_sigma=float(a["bse_noise_sigma"]), inlens_noise_sigma=float(a["inlens_noise_sigma"]),
                   void_threshold=float(a["void_threshold"]), bright_threshold=float(a["bright_threshold"]),
                   bright_mode=float(a["bright_mode"]), bright_mode_found=bool(a["bright_mode_found"]),
                   has_se=raw_se is not None, seed=int(seed))
    return Crop(window, anchors, _phase_maps(h, window["BSE"]), pert, crop_id)


# ----------------------------------------------------------------------------------------------------
# views on disk
# ----------------------------------------------------------------------------------------------------
def _atomic(path, write):
    """write(tmp_path) then rename, so a reader never sees half a file."""
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_name(f".{path.stem}.tmp{os.getpid()}{path.suffix}")
    write(tmp)
    os.replace(tmp, path)


def views_path(crop_id, pert=P0):
    return VIEWS_DIR / pert / f"{crop_id}.npz"


def build_views(crop_id, pert=P0, force=False):
    """Make and store one crop version. Perturbations and injections are applied to the RAW image, then harmonised."""
    path = views_path(crop_id, pert)
    if path.exists() and not force:
        return path
    folder = crops_table().set_index("site").folder[crop_id]
    raw = {d: load_grey(raw_path(folder, crop_id, d)) for d in ("BSE", "Inlens", "SE")}
    r0, r1, x0, x1 = common_window(raw["BSE"].shape)
    seed = zlib.crc32(np.ascontiguousarray(raw["BSE"][r0:r1, x0:x1]).tobytes())   # from P0 content, shared by its perturbations
    bse, inlens, se = raw["BSE"], raw["Inlens"], raw["SE"]
    if pert in IMAGING_PERTS:
        bse, inlens, se = _perturb(bse, pert), _perturb(inlens, pert, seed=1), _perturb(se, pert, seed=2)
    elif pert in MATERIAL_INJECTS:
        bse, inlens = _inject(bse, inlens, H.harmonise_arrays(bse, inlens, se, seed), pert)
    elif pert != P0:
        raise ValueError(f"unknown perturbation {pert!r}")
    crop = make_crop(bse, inlens, se, pert, crop_id, seed)
    _atomic(path, lambda tmp: np.savez(tmp, bse=crop.raw["BSE"], inlens=crop.raw["Inlens"], se=crop.raw["SE"],
                                       anchors=json.dumps(crop.anchors), **{f"m_{k}": np.packbits(v) for k, v in crop.masks.items()}))
    return path


def load_crop(crop_id, pert=P0, build=True):
    path = views_path(crop_id, pert)
    if not path.exists():
        if not build:
            raise FileNotFoundError(path)
        build_views(crop_id, pert)
    z = np.load(path)
    n = WINDOW[0] * WINDOW[1]
    masks = {k[2:]: np.unpackbits(z[k], count=n).reshape(WINDOW).astype(bool) for k in z.files if k.startswith("m_")}
    return Crop({"BSE": z["bse"], "Inlens": z["inlens"], "SE": z["se"]}, json.loads(str(z["anchors"])), masks, pert, crop_id)


# ----------------------------------------------------------------------------------------------------
# what a family returns
# ----------------------------------------------------------------------------------------------------
@dataclass
class FeatureResult:
    """scalars: name -> float.  blocks: name -> array, one per crop (embeddings, spectra, Gram matrices).
    tiles: name -> (n_tiles, d) array, for set kernels.  catalog: one dict per name, built by the three methods."""
    family: str
    scalars: dict = field(default_factory=dict)
    blocks: dict = field(default_factory=dict)
    tiles: dict = field(default_factory=dict)
    catalog: list = field(default_factory=list)
    meta: dict = field(default_factory=dict)       # how it was made (profile, device, precision, versions): kept in .done

    def _add(self, kind, det, view, scale_nm, stat, length_um, layer, tag):
        name = column(self.family, det, view, scale_nm, stat)
        self.catalog.append(dict(name=name, kind=kind, family=self.family, detector=det, view=view, scale_nm=int(scale_nm),
                                 length_um=np.nan if length_um is None else float(length_um), layer=str(layer), tag=tag))
        return name

    def scalar(self, det, view, scale_nm, stat, value, *, length_um=None, layer="", tag="material"):
        """One number. length_um = the physical length the statistic probes (e.g. a GLCM offset), None if it has none."""
        self.scalars[self._add("scalar", det, view, scale_nm, stat, length_um, layer, tag)] = float(value)

    def block(self, det, view, scale_nm, stat, array, *, length_um=None, layer="", tag="material", dtype=np.float32):
        self.blocks[self._add("block", det, view, scale_nm, stat, length_um, layer, tag)] = np.asarray(array, dtype)

    def tile_block(self, det, view, scale_nm, stat, array, *, length_um=None, layer="", tag="material", dtype=np.float32):
        """dtype=np.float16 halves the size of big arrays such as token grids."""
        self.tiles[self._add("tiles", det, view, scale_nm, stat, length_um, layer, tag)] = np.asarray(array, dtype)


def validate(res):
    """Raise ValueError listing every way a FeatureResult breaks the contract."""
    problems = []
    names = [c["name"] for c in res.catalog]
    if len(set(names)) != len(names):
        problems.append("duplicate names in the catalog")
    if set(names) != set(res.scalars) | set(res.blocks) | set(res.tiles):
        problems.append("catalog and values do not list the same names")
    for c in res.catalog:
        if c["tag"] not in TAGS:
            problems.append(f"{c['name']}: tag {c['tag']!r} is not one of {TAGS}")
        if c["detector"] in LEAKRISK_DETECTORS and c["tag"] != "leakrisk":
            problems.append(f"{c['name']}: anything from {c['detector']} must be tagged leakrisk")
        if c["name"].count("|") != 4 or not c["name"].startswith(res.family + "|"):
            problems.append(f"{c['name']}: name must be family|det|view|scale_nm|stat")
        bad = forbidden_tokens(c["name"])
        if bad:
            problems.append(f"{c['name']}: forbidden name part(s) {sorted(bad)}")
    for name, v in res.scalars.items():
        if not np.isfinite(v):
            problems.append(f"{name}: not finite ({v})")
    for name, v in {**res.blocks, **res.tiles}.items():
        if v.size == 0 or not np.isfinite(v).all():
            problems.append(f"{name}: empty or not finite")
    for name, v in res.tiles.items():
        if v.ndim != 2:
            problems.append(f"{name}: tile arrays must be (n_tiles, d), got {v.shape}")
    if problems:
        raise ValueError(f"{res.family}: " + "; ".join(problems[:12]) + (f" (+{len(problems) - 12} more)" if len(problems) > 12 else ""))


def feat_paths(family, crop_id, pert=P0):
    base = FEAT_DIR / family / pert / crop_id
    return base.with_suffix(".parquet"), base.with_suffix(".npz"), base.with_suffix(".done")


def save_result(res, crop_id, pert=P0, seconds=None):
    validate(res)
    parquet, npz, done = feat_paths(res.family, crop_id, pert)
    done.unlink(missing_ok=True)
    _atomic(parquet, lambda tmp: pd.DataFrame([res.scalars], dtype=np.float64).to_parquet(tmp))
    if res.blocks or res.tiles:
        _atomic(npz, lambda tmp: np.savez(tmp, **res.blocks, **res.tiles))
    _atomic(FEAT_DIR / res.family / "catalog.parquet", lambda tmp: pd.DataFrame(res.catalog).to_parquet(tmp))
    done.write_text(json.dumps(dict(n_scalars=len(res.scalars), n_blocks=len(res.blocks), n_tiles=len(res.tiles),
                                    seconds=None if seconds is None else round(seconds, 1), meta=res.meta), default=str))
    STATUS_LOG.parent.mkdir(parents=True, exist_ok=True)
    with open(STATUS_LOG, "a") as f:
        f.write(json.dumps(dict(t=time.strftime("%Y-%m-%dT%H:%M:%S"), family=res.family, pert=pert, crop=crop_id,
                                seconds=None if seconds is None else round(seconds, 1), n_scalars=len(res.scalars),
                                n_blocks=len(res.blocks), n_tiles=len(res.tiles))) + "\n")


def is_done(family, crop_id, pert=P0):
    return feat_paths(family, crop_id, pert)[2].exists()


def load_scalars(family, perts=(P0,), crops=None):
    """Every finished crop version of one family as a DataFrame indexed by (pert, crop). Missing ones are skipped."""
    rows = {}
    for pert in perts:
        for crop_id in crops or all_crops():
            parquet, _, done = feat_paths(family, crop_id, pert)
            if done.exists():
                frame = pd.read_parquet(parquet)
                rows[(pert, crop_id)] = frame.iloc[0] if len(frame) else pd.Series(dtype=float)   # block-only families
    return pd.DataFrame.from_dict(rows, orient="index") if rows else pd.DataFrame()


def load_arrays(family, crop_id, pert=P0):
    """{name: array} of one crop version's blocks and tile arrays ({} if the family has none)."""
    npz = feat_paths(family, crop_id, pert)[1]
    if not npz.exists():
        return {}
    with np.load(npz) as z:
        return {k: z[k] for k in z.files}


def load_catalog(family):
    return pd.read_parquet(FEAT_DIR / family / "catalog.parquet")
